//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyationApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BabyationApp.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddANote {
            get {
                return ResourceManager.GetString("AddANote", resourceCulture);
            }
        }
        
        internal static string AddANoteDescription {
            get {
                return ResourceManager.GetString("AddANoteDescription", resourceCulture);
            }
        }
        
        internal static string AddAnotherBaby {
            get {
                return ResourceManager.GetString("AddAnotherBaby", resourceCulture);
            }
        }
        
        internal static string AddAnotherPeople {
            get {
                return ResourceManager.GetString("AddAnotherPeople", resourceCulture);
            }
        }
        
        internal static string AddAnotherPump {
            get {
                return ResourceManager.GetString("AddAnotherPump", resourceCulture);
            }
        }
        
        internal static string AddMoreMedia {
            get {
                return ResourceManager.GetString("AddMoreMedia", resourceCulture);
            }
        }
        
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        internal static string AddASession {
            get {
                return ResourceManager.GetString("AddASession", resourceCulture);
            }
        }
        
        internal static string TellUsAboutLittleOne {
            get {
                return ResourceManager.GetString("TellUsAboutLittleOne", resourceCulture);
            }
        }
        
        internal static string AddYourChild {
            get {
                return ResourceManager.GetString("AddYourChild", resourceCulture);
            }
        }
        
        internal static string AddAnotherChild {
            get {
                return ResourceManager.GetString("AddAnotherChild", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string AllDone {
            get {
                return ResourceManager.GetString("AllDone", resourceCulture);
            }
        }
        
        internal static string AllModes {
            get {
                return ResourceManager.GetString("AllModes", resourceCulture);
            }
        }
        
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        internal static string AreYouSureToUseThisMilk {
            get {
                return ResourceManager.GetString("AreYouSureToUseThisMilk", resourceCulture);
            }
        }
        
        internal static string AreYouSureWantToDelete {
            get {
                return ResourceManager.GetString("AreYouSureWantToDelete", resourceCulture);
            }
        }
        
        internal static string AreYouSureWantToDeleteReminder {
            get {
                return ResourceManager.GetString("AreYouSureWantToDeleteReminder", resourceCulture);
            }
        }
        
        internal static string AuthenticationFailure {
            get {
                return ResourceManager.GetString("AuthenticationFailure", resourceCulture);
            }
        }
        
        internal static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        internal static string AutoStartUpper {
            get {
                return ResourceManager.GetString("AutoStartUpper", resourceCulture);
            }
        }
        
        internal static string AutoStartPump {
            get {
                return ResourceManager.GetString("AutoStartPump", resourceCulture);
            }
        }
        
        internal static string AutoStartForSession {
            get {
                return ResourceManager.GetString("AutoStartForSession", resourceCulture);
            }
        }
        
        internal static string AutoStartForSessionDescription {
            get {
                return ResourceManager.GetString("AutoStartForSessionDescription", resourceCulture);
            }
        }
        
        internal static string AverageOuncesPerDay {
            get {
                return ResourceManager.GetString("AverageOuncesPerDay", resourceCulture);
            }
        }
        
        internal static string AverageNursedPerDay {
            get {
                return ResourceManager.GetString("AverageNursedPerDay", resourceCulture);
            }
        }
        
        internal static string AverageBottlePerDay {
            get {
                return ResourceManager.GetString("AverageBottlePerDay", resourceCulture);
            }
        }
        
        internal static string BestBy {
            get {
                return ResourceManager.GetString("BestBy", resourceCulture);
            }
        }
        
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        internal static string BreastMilk {
            get {
                return ResourceManager.GetString("BreastMilk", resourceCulture);
            }
        }
        
        internal static string BTStatus {
            get {
                return ResourceManager.GetString("BTStatus", resourceCulture);
            }
        }
        
        internal static string Bottle {
            get {
                return ResourceManager.GetString("Bottle", resourceCulture);
            }
        }
        
        internal static string BottleUpper {
            get {
                return ResourceManager.GetString("BottleUpper", resourceCulture);
            }
        }
        
        internal static string BottleSession {
            get {
                return ResourceManager.GetString("BottleSession", resourceCulture);
            }
        }
        
        internal static string BottleInSession {
            get {
                return ResourceManager.GetString("BottleInSession", resourceCulture);
            }
        }
        
        internal static string BottleBreast {
            get {
                return ResourceManager.GetString("BottleBreast", resourceCulture);
            }
        }
        
        internal static string BottleFormula {
            get {
                return ResourceManager.GetString("BottleFormula", resourceCulture);
            }
        }
        
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        internal static string CalibrateLevelSensors {
            get {
                return ResourceManager.GetString("CalibrateLevelSensors", resourceCulture);
            }
        }
        
        internal static string CalibrationUpdated {
            get {
                return ResourceManager.GetString("CalibrationUpdated", resourceCulture);
            }
        }
        
        internal static string ChangeMyPassword {
            get {
                return ResourceManager.GetString("ChangeMyPassword", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string CharactersLeft {
            get {
                return ResourceManager.GetString("CharactersLeft", resourceCulture);
            }
        }
        
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        internal static string ChooseModeUpper {
            get {
                return ResourceManager.GetString("ChooseModeUpper", resourceCulture);
            }
        }
        
        internal static string ChooseType {
            get {
                return ResourceManager.GetString("ChooseType", resourceCulture);
            }
        }
        
        internal static string ClickToNext {
            get {
                return ResourceManager.GetString("ClickToNext", resourceCulture);
            }
        }
        
        internal static string CombinedTotal {
            get {
                return ResourceManager.GetString("CombinedTotal", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string ConnectToYourPump {
            get {
                return ResourceManager.GetString("ConnectToYourPump", resourceCulture);
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string CreateANewMode {
            get {
                return ResourceManager.GetString("CreateANewMode", resourceCulture);
            }
        }
        
        internal static string CreateNewModeUpper {
            get {
                return ResourceManager.GetString("CreateNewModeUpper", resourceCulture);
            }
        }
        
        internal static string CreateNewReminder {
            get {
                return ResourceManager.GetString("CreateNewReminder", resourceCulture);
            }
        }
        
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        internal static string DarnYourPasswordOrEmailIsNotValid {
            get {
                return ResourceManager.GetString("DarnYourPasswordOrEmailIsNotValid", resourceCulture);
            }
        }
        
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string DateDelimiter {
            get {
                return ResourceManager.GetString("DateDelimiter", resourceCulture);
            }
        }
        
        internal static string DateDelimiter2 {
            get {
                return ResourceManager.GetString("DateDelimiter2", resourceCulture);
            }
        }
        
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        internal static string DescribePumpMode {
            get {
                return ResourceManager.GetString("DescribePumpMode", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DeleteUpper {
            get {
                return ResourceManager.GetString("DeleteUpper", resourceCulture);
            }
        }
        
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        internal static string Duration_Upper {
            get {
                return ResourceManager.GetString("Duration_Upper", resourceCulture);
            }
        }
        
        internal static string EditUpper {
            get {
                return ResourceManager.GetString("EditUpper", resourceCulture);
            }
        }
        
        internal static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        internal static string EnterChildsName {
            get {
                return ResourceManager.GetString("EnterChildsName", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string EmailUpper {
            get {
                return ResourceManager.GetString("EmailUpper", resourceCulture);
            }
        }
        
        internal static string EmailNewPasswordUpper {
            get {
                return ResourceManager.GetString("EmailNewPasswordUpper", resourceCulture);
            }
        }
        
        internal static string DontSweatIt {
            get {
                return ResourceManager.GetString("DontSweatIt", resourceCulture);
            }
        }
        
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        internal static string EmailOnTheWay {
            get {
                return ResourceManager.GetString("EmailOnTheWay", resourceCulture);
            }
        }
        
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        internal static string EnterYourName {
            get {
                return ResourceManager.GetString("EnterYourName", resourceCulture);
            }
        }
        
        internal static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        internal static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        internal static string FactoryReset {
            get {
                return ResourceManager.GetString("FactoryReset", resourceCulture);
            }
        }
        
        internal static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        internal static string FirstTimePumper {
            get {
                return ResourceManager.GetString("FirstTimePumper", resourceCulture);
            }
        }
        
        internal static string ForgetThisDevice {
            get {
                return ResourceManager.GetString("ForgetThisDevice", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        internal static string Freezer {
            get {
                return ResourceManager.GetString("Freezer", resourceCulture);
            }
        }
        
        internal static string Fridge {
            get {
                return ResourceManager.GetString("Fridge", resourceCulture);
            }
        }
        
        internal static string GotMilkHowWouldYouLikeStoreIt {
            get {
                return ResourceManager.GetString("GotMilkHowWouldYouLikeStoreIt", resourceCulture);
            }
        }
        
        internal static string GotMilkHowWouldYouLikeStoreItOptional {
            get {
                return ResourceManager.GetString("GotMilkHowWouldYouLikeStoreItOptional", resourceCulture);
            }
        }
        
        internal static string HelloAndWelcome {
            get {
                return ResourceManager.GetString("HelloAndWelcome", resourceCulture);
            }
        }
        
        internal static string HelpsLetdown {
            get {
                return ResourceManager.GetString("HelpsLetdown", resourceCulture);
            }
        }
        
        internal static string HiMama {
            get {
                return ResourceManager.GetString("HiMama", resourceCulture);
            }
        }
        
        internal static string HistoryUpper {
            get {
                return ResourceManager.GetString("HistoryUpper", resourceCulture);
            }
        }
        
        internal static string HowMuchEat {
            get {
                return ResourceManager.GetString("HowMuchEat", resourceCulture);
            }
        }
        
        internal static string HowWillYouStoreMilk {
            get {
                return ResourceManager.GetString("HowWillYouStoreMilk", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string HoursLower {
            get {
                return ResourceManager.GetString("HoursLower", resourceCulture);
            }
        }
        
        internal static string IfYouRemoveBabyYoullLoseAllData {
            get {
                return ResourceManager.GetString("IfYouRemoveBabyYoullLoseAllData", resourceCulture);
            }
        }
        
        internal static string IHaveReadThe {
            get {
                return ResourceManager.GetString("IHaveReadThe", resourceCulture);
            }
        }
        
        internal static string InJustFewSteps {
            get {
                return ResourceManager.GetString("InJustFewSteps", resourceCulture);
            }
        }
        
        internal static string InvalidEntry {
            get {
                return ResourceManager.GetString("InvalidEntry", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        internal static string Left_Upper {
            get {
                return ResourceManager.GetString("Left_Upper", resourceCulture);
            }
        }
        
        internal static string LeftBreast {
            get {
                return ResourceManager.GetString("LeftBreast", resourceCulture);
            }
        }
        
        internal static string LeftTotal {
            get {
                return ResourceManager.GetString("LeftTotal", resourceCulture);
            }
        }
        
        internal static string Letdown {
            get {
                return ResourceManager.GetString("Letdown", resourceCulture);
            }
        }
        
        internal static string LogPastBottleFeed {
            get {
                return ResourceManager.GetString("LogPastBottleFeed", resourceCulture);
            }
        }
        
        internal static string LogBottleSession {
            get {
                return ResourceManager.GetString("LogBottleSession", resourceCulture);
            }
        }
        
        internal static string LogPastPump {
            get {
                return ResourceManager.GetString("LogPastPump", resourceCulture);
            }
        }
        
        internal static string LogPastNurse {
            get {
                return ResourceManager.GetString("LogPastNurse", resourceCulture);
            }
        }
        
        internal static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        internal static string MinimumLengthRule {
            get {
                return ResourceManager.GetString("MinimumLengthRule", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string MinutesLower {
            get {
                return ResourceManager.GetString("MinutesLower", resourceCulture);
            }
        }
        
        internal static string ModeNameUpper {
            get {
                return ResourceManager.GetString("ModeNameUpper", resourceCulture);
            }
        }
        
        internal static string ModeDescriptionUpper {
            get {
                return ResourceManager.GetString("ModeDescriptionUpper", resourceCulture);
            }
        }
        
        internal static string ModesUpper {
            get {
                return ResourceManager.GetString("ModesUpper", resourceCulture);
            }
        }
        
        internal static string Mom {
            get {
                return ResourceManager.GetString("Mom", resourceCulture);
            }
        }
        
        internal static string MomsEmail {
            get {
                return ResourceManager.GetString("MomsEmail", resourceCulture);
            }
        }
        
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string MyBabies {
            get {
                return ResourceManager.GetString("MyBabies", resourceCulture);
            }
        }
        
        internal static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        internal static string MyInventory {
            get {
                return ResourceManager.GetString("MyInventory", resourceCulture);
            }
        }
        
        internal static string Caregivers {
            get {
                return ResourceManager.GetString("Caregivers", resourceCulture);
            }
        }
        
        internal static string MyProfileUpper {
            get {
                return ResourceManager.GetString("MyProfileUpper", resourceCulture);
            }
        }
        
        internal static string MyReminders {
            get {
                return ResourceManager.GetString("MyReminders", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NameUpper {
            get {
                return ResourceManager.GetString("NameUpper", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string NickNameUpper {
            get {
                return ResourceManager.GetString("NickNameUpper", resourceCulture);
            }
        }
        
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        internal static string NoKeepUpper {
            get {
                return ResourceManager.GetString("NoKeepUpper", resourceCulture);
            }
        }
        
        internal static string NoKeepMyBaby {
            get {
                return ResourceManager.GetString("NoKeepMyBaby", resourceCulture);
            }
        }
        
        internal static string NoKeepThisMilk {
            get {
                return ResourceManager.GetString("NoKeepThisMilk", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string NotePlaceholder {
            get {
                return ResourceManager.GetString("NotePlaceholder", resourceCulture);
            }
        }
        
        internal static string NoteDetails {
            get {
                return ResourceManager.GetString("NoteDetails", resourceCulture);
            }
        }
        
        internal static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        internal static string NoWarriesWeCanUpdateYourPassword {
            get {
                return ResourceManager.GetString("NoWarriesWeCanUpdateYourPassword", resourceCulture);
            }
        }
        
        internal static string NoWorriesWellSendNewPasswordToYourEmail {
            get {
                return ResourceManager.GetString("NoWorriesWellSendNewPasswordToYourEmail", resourceCulture);
            }
        }
        
        internal static string NumericDelimiter {
            get {
                return ResourceManager.GetString("NumericDelimiter", resourceCulture);
            }
        }
        
        internal static string NursingSession {
            get {
                return ResourceManager.GetString("NursingSession", resourceCulture);
            }
        }
        
        internal static string OneFillBothBottlesToOneOzAndClickBelow {
            get {
                return ResourceManager.GetString("OneFillBothBottlesToOneOzAndClickBelow", resourceCulture);
            }
        }
        
        internal static string OneSymbolRule {
            get {
                return ResourceManager.GetString("OneSymbolRule", resourceCulture);
            }
        }
        
        internal static string OnUpper {
            get {
                return ResourceManager.GetString("OnUpper", resourceCulture);
            }
        }
        
        internal static string OffUpper {
            get {
                return ResourceManager.GetString("OffUpper", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string Ounces {
            get {
                return ResourceManager.GetString("Ounces", resourceCulture);
            }
        }
        
        internal static string OuncesLower {
            get {
                return ResourceManager.GetString("OuncesLower", resourceCulture);
            }
        }
        
        internal static string OuncesPumped {
            get {
                return ResourceManager.GetString("OuncesPumped", resourceCulture);
            }
        }
        
        internal static string PairPump {
            get {
                return ResourceManager.GetString("PairPump", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        internal static string PhaseUpper {
            get {
                return ResourceManager.GetString("PhaseUpper", resourceCulture);
            }
        }
        
        internal static string PerSession {
            get {
                return ResourceManager.GetString("PerSession", resourceCulture);
            }
        }
        
        internal static string PlusSign {
            get {
                return ResourceManager.GetString("PlusSign", resourceCulture);
            }
        }
        
        internal static string Prefered {
            get {
                return ResourceManager.GetString("Prefered", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyTermsOfService {
            get {
                return ResourceManager.GetString("PrivacyPolicyTermsOfService", resourceCulture);
            }
        }
        
        internal static string ProblemsIndentified {
            get {
                return ResourceManager.GetString("ProblemsIndentified", resourceCulture);
            }
        }
        
        internal static string Pump {
            get {
                return ResourceManager.GetString("Pump", resourceCulture);
            }
        }
        
        internal static string Pumping {
            get {
                return ResourceManager.GetString("Pumping", resourceCulture);
            }
        }
        
        internal static string PumpingUpper {
            get {
                return ResourceManager.GetString("PumpingUpper", resourceCulture);
            }
        }
        
        internal static string PumpingSession_Upper {
            get {
                return ResourceManager.GetString("PumpingSession_Upper", resourceCulture);
            }
        }
        
        internal static string PumpDetected {
            get {
                return ResourceManager.GetString("PumpDetected", resourceCulture);
            }
        }
        
        internal static string PumpingAverages {
            get {
                return ResourceManager.GetString("PumpingAverages", resourceCulture);
            }
        }
        
        internal static string PumpInUse {
            get {
                return ResourceManager.GetString("PumpInUse", resourceCulture);
            }
        }
        
        internal static string PumpLater {
            get {
                return ResourceManager.GetString("PumpLater", resourceCulture);
            }
        }
        
        internal static string PumpMode {
            get {
                return ResourceManager.GetString("PumpMode", resourceCulture);
            }
        }
        
        internal static string PumpPhase {
            get {
                return ResourceManager.GetString("PumpPhase", resourceCulture);
            }
        }
        
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        internal static string ScheduleSession {
            get {
                return ResourceManager.GetString("ScheduleSession", resourceCulture);
            }
        }
        
        internal static string SchedulePumpSessionUpper {
            get {
                return ResourceManager.GetString("SchedulePumpSessionUpper", resourceCulture);
            }
        }
        
        internal static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        internal static string RemoveBaby {
            get {
                return ResourceManager.GetString("RemoveBaby", resourceCulture);
            }
        }
        
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        internal static string Right_Upper {
            get {
                return ResourceManager.GetString("Right_Upper", resourceCulture);
            }
        }
        
        internal static string RightBreast {
            get {
                return ResourceManager.GetString("RightBreast", resourceCulture);
            }
        }
        
        internal static string RightTotal {
            get {
                return ResourceManager.GetString("RightTotal", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        internal static string Side {
            get {
                return ResourceManager.GetString("Side", resourceCulture);
            }
        }
        
        internal static string SavedPumpMode {
            get {
                return ResourceManager.GetString("SavedPumpMode", resourceCulture);
            }
        }
        
        internal static string SavedBottleSession {
            get {
                return ResourceManager.GetString("SavedBottleSession", resourceCulture);
            }
        }
        
        internal static string SavedNursingSession {
            get {
                return ResourceManager.GetString("SavedNursingSession", resourceCulture);
            }
        }
        
        internal static string SavePastPump {
            get {
                return ResourceManager.GetString("SavePastPump", resourceCulture);
            }
        }
        
        internal static string SaveReminder {
            get {
                return ResourceManager.GetString("SaveReminder", resourceCulture);
            }
        }
        
        internal static string SaveThisMode {
            get {
                return ResourceManager.GetString("SaveThisMode", resourceCulture);
            }
        }
        
        internal static string SaveThisNote {
            get {
                return ResourceManager.GetString("SaveThisNote", resourceCulture);
            }
        }
        
        internal static string SaveThisSession {
            get {
                return ResourceManager.GetString("SaveThisSession", resourceCulture);
            }
        }
        
        internal static string SessionNameUpper {
            get {
                return ResourceManager.GetString("SessionNameUpper", resourceCulture);
            }
        }
        
        internal static string SelectChild {
            get {
                return ResourceManager.GetString("SelectChild", resourceCulture);
            }
        }
        
        internal static string SelectedMode_Upper {
            get {
                return ResourceManager.GetString("SelectedMode_Upper", resourceCulture);
            }
        }
        
        internal static string SelectedChild {
            get {
                return ResourceManager.GetString("SelectedChild", resourceCulture);
            }
        }
        
        internal static string SelectSound {
            get {
                return ResourceManager.GetString("SelectSound", resourceCulture);
            }
        }
        
        internal static string SelectDateUpper {
            get {
                return ResourceManager.GetString("SelectDateUpper", resourceCulture);
            }
        }
        
        internal static string SelectTimeUpper {
            get {
                return ResourceManager.GetString("SelectTimeUpper", resourceCulture);
            }
        }
        
        internal static string SelectYourSides {
            get {
                return ResourceManager.GetString("SelectYourSides", resourceCulture);
            }
        }
        
        internal static string SetCalibrationPointOne {
            get {
                return ResourceManager.GetString("SetCalibrationPointOne", resourceCulture);
            }
        }
        
        internal static string SetCalibrationPointTwo {
            get {
                return ResourceManager.GetString("SetCalibrationPointTwo", resourceCulture);
            }
        }
        
        internal static string SetTime {
            get {
                return ResourceManager.GetString("SetTime", resourceCulture);
            }
        }
        
        internal static string SetTimer {
            get {
                return ResourceManager.GetString("SetTimer", resourceCulture);
            }
        }
        
        internal static string SettingsUpper {
            get {
                return ResourceManager.GetString("SettingsUpper", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string SignInWithFacebook {
            get {
                return ResourceManager.GetString("SignInWithFacebook", resourceCulture);
            }
        }
        
        internal static string SignInWithGoogle {
            get {
                return ResourceManager.GetString("SignInWithGoogle", resourceCulture);
            }
        }
        
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string SignUpViaEmail {
            get {
                return ResourceManager.GetString("SignUpViaEmail", resourceCulture);
            }
        }
        
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        internal static string StartTime_Upper {
            get {
                return ResourceManager.GetString("StartTime_Upper", resourceCulture);
            }
        }
        
        internal static string StopFeeding {
            get {
                return ResourceManager.GetString("StopFeeding", resourceCulture);
            }
        }
        
        internal static string StopNursing {
            get {
                return ResourceManager.GetString("StopNursing", resourceCulture);
            }
        }
        
        internal static string StopPumping {
            get {
                return ResourceManager.GetString("StopPumping", resourceCulture);
            }
        }
        
        internal static string Suction {
            get {
                return ResourceManager.GetString("Suction", resourceCulture);
            }
        }
        
        internal static string TapSideToBegin {
            get {
                return ResourceManager.GetString("TapSideToBegin", resourceCulture);
            }
        }
        
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        internal static string TermsServiceTopLargeTitle {
            get {
                return ResourceManager.GetString("TermsServiceTopLargeTitle", resourceCulture);
            }
        }
        
        internal static string TestMenu {
            get {
                return ResourceManager.GetString("TestMenu", resourceCulture);
            }
        }
        
        internal static string ThisCanNotBeUndone {
            get {
                return ResourceManager.GetString("ThisCanNotBeUndone", resourceCulture);
            }
        }
        
        internal static string ThisPumpNamed {
            get {
                return ResourceManager.GetString("ThisPumpNamed", resourceCulture);
            }
        }
        
        internal static string ThisWillDeleteFromInventory {
            get {
                return ResourceManager.GetString("ThisWillDeleteFromInventory", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string TimeDelimiter {
            get {
                return ResourceManager.GetString("TimeDelimiter", resourceCulture);
            }
        }
        
        internal static string TimeDelimiter2 {
            get {
                return ResourceManager.GetString("TimeDelimiter2", resourceCulture);
            }
        }
        
        internal static string TimeToGivePumpName {
            get {
                return ResourceManager.GetString("TimeToGivePumpName", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string Total_Upper {
            get {
                return ResourceManager.GetString("Total_Upper", resourceCulture);
            }
        }
        
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        internal static string TotalDuration {
            get {
                return ResourceManager.GetString("TotalDuration", resourceCulture);
            }
        }
        
        internal static string TotalFed {
            get {
                return ResourceManager.GetString("TotalFed", resourceCulture);
            }
        }
        
        internal static string TotalOunces {
            get {
                return ResourceManager.GetString("TotalOunces", resourceCulture);
            }
        }
        
        internal static string TotalPumpTime {
            get {
                return ResourceManager.GetString("TotalPumpTime", resourceCulture);
            }
        }
        
        internal static string Trash {
            get {
                return ResourceManager.GetString("Trash", resourceCulture);
            }
        }
        
        internal static string TwoCharactersRule {
            get {
                return ResourceManager.GetString("TwoCharactersRule", resourceCulture);
            }
        }
        
        internal static string TwoDigitsRule {
            get {
                return ResourceManager.GetString("TwoDigitsRule", resourceCulture);
            }
        }
        
        internal static string TwoFillBothBottlesToFiveOzAndClickBelow {
            get {
                return ResourceManager.GetString("TwoFillBothBottlesToFiveOzAndClickBelow", resourceCulture);
            }
        }
        
        internal static string UpdateDevice {
            get {
                return ResourceManager.GetString("UpdateDevice", resourceCulture);
            }
        }
        
        internal static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
        
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        internal static string VideoTutorial {
            get {
                return ResourceManager.GetString("VideoTutorial", resourceCulture);
            }
        }
        
        internal static string VistOurSite {
            get {
                return ResourceManager.GetString("VistOurSite", resourceCulture);
            }
        }
        
        internal static string WantPreview {
            get {
                return ResourceManager.GetString("WantPreview", resourceCulture);
            }
        }
        
        internal static string WatchThe {
            get {
                return ResourceManager.GetString("WatchThe", resourceCulture);
            }
        }
        
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        internal static string WeeklyTotal {
            get {
                return ResourceManager.GetString("WeeklyTotal", resourceCulture);
            }
        }
        
        internal static string WhatShouldCallCutie {
            get {
                return ResourceManager.GetString("WhatShouldCallCutie", resourceCulture);
            }
        }
        
        internal static string WhatTypeOfMilk {
            get {
                return ResourceManager.GetString("WhatTypeOfMilk", resourceCulture);
            }
        }
        
        internal static string WhatWillYouCallThisMode {
            get {
                return ResourceManager.GetString("WhatWillYouCallThisMode", resourceCulture);
            }
        }
        
        internal static string WhatWillYouCallThisPump {
            get {
                return ResourceManager.GetString("WhatWillYouCallThisPump", resourceCulture);
            }
        }
        
        internal static string WhatWouldYouLikeNameThis {
            get {
                return ResourceManager.GetString("WhatWouldYouLikeNameThis", resourceCulture);
            }
        }
        
        internal static string WouldYouLikeAddDescription {
            get {
                return ResourceManager.GetString("WouldYouLikeAddDescription", resourceCulture);
            }
        }
        
        internal static string WouldYouLikeToSaveThisExperienceAsNewMode {
            get {
                return ResourceManager.GetString("WouldYouLikeToSaveThisExperienceAsNewMode", resourceCulture);
            }
        }
        
        internal static string WriteMoreAboutModeHere {
            get {
                return ResourceManager.GetString("WriteMoreAboutModeHere", resourceCulture);
            }
        }
        
        internal static string WriteNameHere {
            get {
                return ResourceManager.GetString("WriteNameHere", resourceCulture);
            }
        }
        
        internal static string WriteYourPassword {
            get {
                return ResourceManager.GetString("WriteYourPassword", resourceCulture);
            }
        }
        
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        internal static string YesDeleteUpper {
            get {
                return ResourceManager.GetString("YesDeleteUpper", resourceCulture);
            }
        }
        
        internal static string YesDeleteMyBaby {
            get {
                return ResourceManager.GetString("YesDeleteMyBaby", resourceCulture);
            }
        }
        
        internal static string YesSaveAsNewMode {
            get {
                return ResourceManager.GetString("YesSaveAsNewMode", resourceCulture);
            }
        }
        
        internal static string YesUseNow {
            get {
                return ResourceManager.GetString("YesUseNow", resourceCulture);
            }
        }
        
        internal static string YouMadeSomeChangesToPumpMode {
            get {
                return ResourceManager.GetString("YouMadeSomeChangesToPumpMode", resourceCulture);
            }
        }
        
        internal static string YouMadeSomeEdits {
            get {
                return ResourceManager.GetString("YouMadeSomeEdits", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string EnterNamePumpingMode {
            get {
                return ResourceManager.GetString("EnterNamePumpingMode", resourceCulture);
            }
        }
        
        internal static string EnterNicknameForSession {
            get {
                return ResourceManager.GetString("EnterNicknameForSession", resourceCulture);
            }
        }
        
        internal static string EnterPumpNickname {
            get {
                return ResourceManager.GetString("EnterPumpNickname", resourceCulture);
            }
        }
        
        internal static string IfThePasskeyMatchecOnPump {
            get {
                return ResourceManager.GetString("IfThePasskeyMatchecOnPump", resourceCulture);
            }
        }
        
        internal static string NameYourPump {
            get {
                return ResourceManager.GetString("NameYourPump", resourceCulture);
            }
        }
        
        internal static string PairYouPumpOptional {
            get {
                return ResourceManager.GetString("PairYouPumpOptional", resourceCulture);
            }
        }
        
        internal static string PumpName {
            get {
                return ResourceManager.GetString("PumpName", resourceCulture);
            }
        }
        
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        internal static string WhatYouWantCallThePump {
            get {
                return ResourceManager.GetString("WhatYouWantCallThePump", resourceCulture);
            }
        }
        
        internal static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionText {
            get {
                return ResourceManager.GetString("TermsAndConditionText", resourceCulture);
            }
        }
        
        internal static string AboutUpper {
            get {
                return ResourceManager.GetString("AboutUpper", resourceCulture);
            }
        }
        
        internal static string AboutBabyation {
            get {
                return ResourceManager.GetString("AboutBabyation", resourceCulture);
            }
        }
        
        internal static string AboutBabyationUpper {
            get {
                return ResourceManager.GetString("AboutBabyationUpper", resourceCulture);
            }
        }
        
        internal static string ByBabyationLower {
            get {
                return ResourceManager.GetString("ByBabyationLower", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        internal static string MyPumps {
            get {
                return ResourceManager.GetString("MyPumps", resourceCulture);
            }
        }
        
        internal static string MyScheduleUpper {
            get {
                return ResourceManager.GetString("MyScheduleUpper", resourceCulture);
            }
        }
        
        internal static string WhoAreYouFeeding {
            get {
                return ResourceManager.GetString("WhoAreYouFeeding", resourceCulture);
            }
        }
        
        internal static string FromTheOptional {
            get {
                return ResourceManager.GetString("FromTheOptional", resourceCulture);
            }
        }
        
        internal static string Feeding {
            get {
                return ResourceManager.GetString("Feeding", resourceCulture);
            }
        }
        
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        internal static string Nursing {
            get {
                return ResourceManager.GetString("Nursing", resourceCulture);
            }
        }
        
        internal static string NursingUpper {
            get {
                return ResourceManager.GetString("NursingUpper", resourceCulture);
            }
        }
        
        internal static string PastFeed {
            get {
                return ResourceManager.GetString("PastFeed", resourceCulture);
            }
        }
        
        internal static string PastNurse {
            get {
                return ResourceManager.GetString("PastNurse", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string DurationLeftSide {
            get {
                return ResourceManager.GetString("DurationLeftSide", resourceCulture);
            }
        }
        
        internal static string DurationRightSide {
            get {
                return ResourceManager.GetString("DurationRightSide", resourceCulture);
            }
        }
        
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        internal static string ModeUpper {
            get {
                return ResourceManager.GetString("ModeUpper", resourceCulture);
            }
        }
        
        internal static string Modes {
            get {
                return ResourceManager.GetString("Modes", resourceCulture);
            }
        }
        
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        internal static string InventoryUpper {
            get {
                return ResourceManager.GetString("InventoryUpper", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        internal static string LogPastSession {
            get {
                return ResourceManager.GetString("LogPastSession", resourceCulture);
            }
        }
        
        internal static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        internal static string SessionUpper {
            get {
                return ResourceManager.GetString("SessionUpper", resourceCulture);
            }
        }
        
        internal static string DashboardUpper {
            get {
                return ResourceManager.GetString("DashboardUpper", resourceCulture);
            }
        }
        
        internal static string FeedUpper {
            get {
                return ResourceManager.GetString("FeedUpper", resourceCulture);
            }
        }
        
        internal static string NoChildError {
            get {
                return ResourceManager.GetString("NoChildError", resourceCulture);
            }
        }
        
        internal static string PairPumpUpper {
            get {
                return ResourceManager.GetString("PairPumpUpper", resourceCulture);
            }
        }
        
        internal static string PairYouPump {
            get {
                return ResourceManager.GetString("PairYouPump", resourceCulture);
            }
        }
        
        internal static string PumpingModes {
            get {
                return ResourceManager.GetString("PumpingModes", resourceCulture);
            }
        }
        
        internal static string PumpingMode {
            get {
                return ResourceManager.GetString("PumpingMode", resourceCulture);
            }
        }
        
        internal static string LeftSide {
            get {
                return ResourceManager.GetString("LeftSide", resourceCulture);
            }
        }
        
        internal static string RightSide {
            get {
                return ResourceManager.GetString("RightSide", resourceCulture);
            }
        }
        
        internal static string FedBy {
            get {
                return ResourceManager.GetString("FedBy", resourceCulture);
            }
        }
        
        internal static string NoWeeklyRecordedActivity {
            get {
                return ResourceManager.GetString("NoWeeklyRecordedActivity", resourceCulture);
            }
        }
        
        internal static string NoDailyRecordedActivity {
            get {
                return ResourceManager.GetString("NoDailyRecordedActivity", resourceCulture);
            }
        }
        
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        internal static string Stimulation {
            get {
                return ResourceManager.GetString("Stimulation", resourceCulture);
            }
        }
        
        internal static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        internal static string BabyationModes {
            get {
                return ResourceManager.GetString("BabyationModes", resourceCulture);
            }
        }
        
        internal static string SelectPumpingMode {
            get {
                return ResourceManager.GetString("SelectPumpingMode", resourceCulture);
            }
        }
        
        internal static string EditYourPumpingModes {
            get {
                return ResourceManager.GetString("EditYourPumpingModes", resourceCulture);
            }
        }
        
        internal static string EnterYourNote {
            get {
                return ResourceManager.GetString("EnterYourNote", resourceCulture);
            }
        }
        
        internal static string ChangePhase_Upper {
            get {
                return ResourceManager.GetString("ChangePhase_Upper", resourceCulture);
            }
        }
        
        internal static string LogPumpingSessionUpper {
            get {
                return ResourceManager.GetString("LogPumpingSessionUpper", resourceCulture);
            }
        }
        
        internal static string AmountLeftSideUpper {
            get {
                return ResourceManager.GetString("AmountLeftSideUpper", resourceCulture);
            }
        }
        
        internal static string AmountRightSideUpper {
            get {
                return ResourceManager.GetString("AmountRightSideUpper", resourceCulture);
            }
        }
        
        internal static string WhatDidYouDoWithMilk {
            get {
                return ResourceManager.GetString("WhatDidYouDoWithMilk", resourceCulture);
            }
        }
        
        internal static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        internal static string CreateNewPassword {
            get {
                return ResourceManager.GetString("CreateNewPassword", resourceCulture);
            }
        }
        
        internal static string EnterYourCurrentPassword {
            get {
                return ResourceManager.GetString("EnterYourCurrentPassword", resourceCulture);
            }
        }
        
        internal static string YouNeedLogBackWithNewPass {
            get {
                return ResourceManager.GetString("YouNeedLogBackWithNewPass", resourceCulture);
            }
        }
        
        internal static string MyMedia_Upper {
            get {
                return ResourceManager.GetString("MyMedia_Upper", resourceCulture);
            }
        }
        
        internal static string EditMyMedia_Upper {
            get {
                return ResourceManager.GetString("EditMyMedia_Upper", resourceCulture);
            }
        }
        
        internal static string EditMedia {
            get {
                return ResourceManager.GetString("EditMedia", resourceCulture);
            }
        }
        
        internal static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        internal static string NowUpper {
            get {
                return ResourceManager.GetString("NowUpper", resourceCulture);
            }
        }
        
        internal static string NoCamera {
            get {
                return ResourceManager.GetString("NoCamera", resourceCulture);
            }
        }
        
        internal static string CameraPermissionsDenied {
            get {
                return ResourceManager.GetString("CameraPermissionsDenied", resourceCulture);
            }
        }
        
        internal static string PhotoPermissionsDenied {
            get {
                return ResourceManager.GetString("PhotoPermissionsDenied", resourceCulture);
            }
        }
        
        internal static string PrimaryAccount {
            get {
                return ResourceManager.GetString("PrimaryAccount", resourceCulture);
            }
        }
        
        internal static string CaregiverAccount {
            get {
                return ResourceManager.GetString("CaregiverAccount", resourceCulture);
            }
        }
        
        internal static string RemoveFromAccount {
            get {
                return ResourceManager.GetString("RemoveFromAccount", resourceCulture);
            }
        }
        
        internal static string AddAuthCode {
            get {
                return ResourceManager.GetString("AddAuthCode", resourceCulture);
            }
        }
        
        internal static string AuthorizedCaregiverUpper {
            get {
                return ResourceManager.GetString("AuthorizedCaregiverUpper", resourceCulture);
            }
        }
        
        internal static string AddAuthCodeTitle {
            get {
                return ResourceManager.GetString("AddAuthCodeTitle", resourceCulture);
            }
        }
        
        internal static string AddAuthCodeDetails {
            get {
                return ResourceManager.GetString("AddAuthCodeDetails", resourceCulture);
            }
        }
        
        internal static string AuthCodeUpper {
            get {
                return ResourceManager.GetString("AuthCodeUpper", resourceCulture);
            }
        }
        
        internal static string AddCodeFromEmail {
            get {
                return ResourceManager.GetString("AddCodeFromEmail", resourceCulture);
            }
        }
        
        internal static string AuthCodeOnTheWay {
            get {
                return ResourceManager.GetString("AuthCodeOnTheWay", resourceCulture);
            }
        }
        
        internal static string InviteCaregiverTitle {
            get {
                return ResourceManager.GetString("InviteCaregiverTitle", resourceCulture);
            }
        }
        
        internal static string InviteCaregiverDetails {
            get {
                return ResourceManager.GetString("InviteCaregiverDetails", resourceCulture);
            }
        }
        
        internal static string EnterCaregiversEmail {
            get {
                return ResourceManager.GetString("EnterCaregiversEmail", resourceCulture);
            }
        }
        
        internal static string AddCaregiverUpper {
            get {
                return ResourceManager.GetString("AddCaregiverUpper", resourceCulture);
            }
        }
        
        internal static string InviteOnTheWay {
            get {
                return ResourceManager.GetString("InviteOnTheWay", resourceCulture);
            }
        }
        
        internal static string AddCaregiver {
            get {
                return ResourceManager.GetString("AddCaregiver", resourceCulture);
            }
        }
        
        internal static string RemoveCaregiver {
            get {
                return ResourceManager.GetString("RemoveCaregiver", resourceCulture);
            }
        }
        
        internal static string AreYouSureRemoveCaregiver {
            get {
                return ResourceManager.GetString("AreYouSureRemoveCaregiver", resourceCulture);
            }
        }
        
        internal static string YesRemoveUpper {
            get {
                return ResourceManager.GetString("YesRemoveUpper", resourceCulture);
            }
        }
        
        internal static string AreYouSureRemoveYourselfCaregiver {
            get {
                return ResourceManager.GetString("AreYouSureRemoveYourselfCaregiver", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string LoggedAsUpper {
            get {
                return ResourceManager.GetString("LoggedAsUpper", resourceCulture);
            }
        }
        
        internal static string Caregiver {
            get {
                return ResourceManager.GetString("Caregiver", resourceCulture);
            }
        }
        
        internal static string SwapAccountsUpper {
            get {
                return ResourceManager.GetString("SwapAccountsUpper", resourceCulture);
            }
        }
    }
}
